Track sources
geostyler/geostyler-mapbox-parser pull request #289
Opened 2023-09-05 09:41 UTC by jansule

This keeps track of the `source` and `layer-source` properties of a mapbox style layer. Through this, we are able to keep the references to sources and source-layers to/from rules when parsing multiple times. This also enables the assignment of geostyler rules to specific sources, which is needed when creating new styling instructions that were not yet present in a mapbox style.

BREAKING CHANGE: This makes the previously omitted `source` property of a mapbox style required. So we are actually conformant with the mapbox style specification in that regard. This breaking change probably affected mostly our tests, which were adjusted.

depends on https://github.com/geostyler/geostyler-mapbox-parser/pull/287

2023-09-05 09:54 UTC, ocruze approved these changes

2023-09-05 10:02 UTC, KaiVolland requested changes
Nice enhancement.

2023-09-05 10:02 UTC, KaiVolland commented on src/MapboxStyleParser.ts
> +    if (splitSymbolizers.length) {
Function arguments should not be mutated. Return a clone with the new values instead.

2023-09-11 08:07 UTC, jansule commented
Thanks for the reviews. @KaiVolland could you take another look at the code? I just rebased against current master and applied some changes

2023-09-11 08:10 UTC, KaiVolland approved these changes

2023-09-11 08:17 UTC, merged